import { Regions } from "src/app/types/regions";

export const regions: Regions[]= [
  {
      "id": 0,
      "departamento": "Amazonas",
      "ciudades": [
          "Leticia",
          "Puerto Nariño",
          "El Encanto",
          "La Chorrera",
          "La Pedrera",
          "La Victoria",
          "Miriti - Paraná",
          "Puerto Alegría",
          "Puerto Arica",
          "Puerto Santander",
          "Tarapacá"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 1,
      "departamento": "Antioquia",
      "ciudades": [
          "Abejorral",
          "Abriaquí",
          "Alejandría",
          "Amagá",
          "Amalfi",
          "Andes",
          "Angelópolis",
          "Angostura",
          "Anorí",
          "Anza",
          "Apartadó",
          "Arboletes",
          "Argelia",
          "Armenia",
          "Barbosa",
          "Bello",
          "Belmira",
          "Betania",
          "Betulia",
          "Briceño",
          "Buriticá",
          "Cáceres",
          "Caicedo",
          "Caldas",
          "Campamento",
          "Cañasgordas",
          "Caracolí",
          "Caramanta",
          "Carepa",
          "Carolina",
          "Caucasia",
          "Chigorodó",
          "Cisneros",
          "Ciudad Bolívar",
          "Cocorná",
          "Concepción",
          "Concordia",
          "Copacabana",
          "Dabeiba",
          "Don Matías",
          "Ebéjico",
          "El Bagre",
          "El Carmen De Viboral",
          "Peñol",
          "Retiro",
          "El Santuario",
          "Entrerrios",
          "Envigado",
          "Fredonia",
          "Frontino",
          "Giraldo",
          "Girardota",
          "Gómez Plata",
          "Granada",
          "Guadalupe",
          "Guarne",
          "Guatape",
          "Heliconia",
          "Hispania",
          "Itagui",
          "Ituango",
          "Jardín",
          "Jericó",
          "La Ceja",
          "La Estrella",
          "La Pintada",
          "La Unión",
          "Liborina",
          "Maceo",
          "Marinilla",
          "Medellín",
          "Montebello",
          "Murindó",
          "Mutatá",
          "Nariño",
          "Nechí",
          "Necoclí",
          "Olaya",
          "Peque",
          "Pueblorrico",
          "Puerto Berrío",
          "Puerto Nare",
          "Puerto Triunfo",
          "Remedios",
          "Rionegro",
          "Sabanalarga",
          "Sabaneta",
          "Salgar",
          "San Andrés",
          "San Carlos",
          "San Francisco",
          "San Jerónimo",
          "San José De La Montaña",
          "San Juan De Urabá",
          "San Luis",
          "San Pedro De Uraba",
          "San Pedro",
          "San Rafael",
          "San Roque",
          "San Vicente",
          "Santa Bárbara",
          "Santafé De Antioquia",
          "Santa Rosa De Osos",
          "Santo Domingo",
          "Segovia",
          "Sonson",
          "Sopetrán",
          "Támesis",
          "Tarazá",
          "Tarso",
          "Titiribí",
          "Toledo",
          "Turbo",
          "Uramita",
          "Urrao",
          "Valdivia",
          "Valparaíso",
          "Vegachí",
          "Venecia",
          "Vigía Del Fuerte",
          "Yalí",
          "Yarumal",
          "Yolombó",
          "Yondó",
          "Zaragoza"
      ],
      "indicativo_fijo": "604"
  },
  {
      "id": 2,
      "departamento": "Arauca",
      "ciudades": [
          "Arauca",
          "Arauquita",
          "Cravo Norte",
          "Fortul",
          "Puerto Rondón",
          "Saravena",
          "Tame"
      ],
      "indicativo_fijo": "607"
  },
  {
      "id": 3,
      "departamento": "Atlántico",
      "ciudades": [
          "Baranoa",
          "Barranquilla",
          "Campo De La Cruz",
          "Candelaria",
          "Galapa",
          "Juan De Acosta",
          "Luruaco",
          "Malambo",
          "Manatí",
          "Palmar De Varela",
          "Piojó",
          "Polonuevo",
          "Ponedera",
          "Puerto Colombia",
          "Repelón",
          "Sabanagrande",
          "Sabanalarga",
          "Santa Lucía",
          "Santo Tomás",
          "Soledad",
          "Suan",
          "Tubará",
          "Usiacurí"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 4,
      "departamento": "Bolívar",
      "ciudades": [
          "Achí",
          "Altos Del Rosario",
          "Arenal",
          "Arjona",
          "Arroyohondo",
          "Barranco De Loba",
          "Brazuelo De Papayal",
          "Calamar",
          "Cantagallo",
          "Cartagena",
          "Cicuco",
          "Clemencia",
          "Córdoba",
          "El Carmen De Bolívar",
          "El Guamo",
          "El Peñón",
          "Hatillo De Loba",
          "Magangué",
          "Mahates",
          "Margarita",
          "María La Baja",
          "Mompós",
          "Montecristo",
          "Morales",
          "Norosí",
          "Pinillos",
          "Regidor",
          "Río Viejo",
          "San Cristóbal",
          "San Estanislao",
          "San Fernando",
          "San Jacinto Del Cauca",
          "San Jacinto",
          "San Juan Nepomuceno",
          "San Martín De Loba",
          "San Pablo",
          "Santa Catalina",
          "Santa Rosa",
          "Santa Rosa Del Sur",
          "Simití",
          "Soplaviento",
          "Talaigua Nuevo",
          "Tiquisio",
          "Turbaco",
          "Turbaná",
          "Villanueva",
          "Zambrano"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 5,
      "departamento": "Boyacá",
      "ciudades": [
          "Almeida",
          "Aquitania",
          "Arcabuco",
          "Belén",
          "Berbeo",
          "Betéitiva",
          "Boavita",
          "Boyacá",
          "Briceño",
          "Buenavista",
          "Busbanzá",
          "Caldas",
          "Campohermoso",
          "Cerinza",
          "Chinavita",
          "Chiquinquirá",
          "Chíquiza",
          "Chiscas",
          "Chita",
          "Chitaraque",
          "Chivatá",
          "Chivor",
          "Ciénega",
          "Cómbita",
          "Coper",
          "Corrales",
          "Covarachía",
          "Cubará",
          "Cucaita",
          "Cuítiva",
          "Duitama",
          "El Cocuy",
          "El Espino",
          "Firavitoba",
          "Floresta",
          "Gachantivá",
          "Gámeza",
          "Garagoa",
          "Guacamayas",
          "Guateque",
          "Guayatá",
          "Güicán",
          "Iza",
          "Jenesano",
          "Jericó",
          "La Capilla",
          "La Uvita",
          "La Victoria",
          "Labranzagrande",
          "Macanal",
          "Maripí",
          "Miraflores",
          "Mongua",
          "Monguí",
          "Moniquirá",
          "Motavita",
          "Muzo",
          "Nobsa",
          "Nuevo Colón",
          "Oicatá",
          "Otanche",
          "Pachavita",
          "Páez",
          "Paipa",
          "Pajarito",
          "Panqueba",
          "Pauna",
          "Paya",
          "Paz De Río",
          "Pesca",
          "Pisba",
          "Puerto Boyacá",
          "Quípama",
          "Ramiriquí",
          "Ráquira",
          "Rondón",
          "Saboyá",
          "Sáchica",
          "Samacá",
          "San Eduardo",
          "San José De Pare",
          "San Luis De Gaceno",
          "San Mateo",
          "San Miguel De Sema",
          "San Pablo De Borbur",
          "Santa María",
          "Santa Rosa De Viterbo",
          "Santa Sofía",
          "Santana",
          "Sativanorte",
          "Sativasur",
          "Siachoque",
          "Soatá",
          "Socha",
          "Socotá",
          "Sogamoso",
          "Somondoco",
          "Sora",
          "Soracá",
          "Sotaquirá",
          "Susacón",
          "Sutamarchán",
          "Sutatenza",
          "Tasco",
          "Tenza",
          "Tibaná",
          "Tibasosa",
          "Tinjacá",
          "Tipacoque",
          "Toca",
          "Togüí",
          "Tópaga",
          "Tota",
          "Tunja",
          "Tununguá",
          "Turmequé",
          "Tuta",
          "Tutazá",
          "Úmbita",
          "Ventaquemada",
          "Villa De Leyva",
          "Viracachá",
          "Zetaquira",
          "Gameza",
          "Umbita"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 6,
      "departamento": "Caldas",
      "ciudades": [
          "Aguadas",
          "Anserma",
          "Aranzazu",
          "Belalcázar",
          "Chinchiná",
          "Filadelfia",
          "La Dorada",
          "La Merced",
          "Manizales",
          "Manzanares",
          "Marmato",
          "Marquetalia",
          "Marulanda",
          "Neira",
          "Norcasia",
          "Pácora",
          "Palestina",
          "Pensilvania",
          "Riosucio",
          "Risaralda",
          "Salamina",
          "Samaná",
          "San José",
          "Supía",
          "Victoria",
          "Villamaría",
          "Viterbo"
      ],
      "indicativo_fijo": "606"
  },
  {
      "id": 7,
      "departamento": "Caquetá",
      "ciudades": [
          "Albania",
          "Belén De Los Andaquíes",
          "Cartagena Del Chairá",
          "Curillo",
          "El Doncello",
          "El Paujil",
          "Florencia",
          "La Montañita",
          "Milán",
          "Morelia",
          "Puerto Rico",
          "San José Del Fragua",
          "San Vicente Del Caguán",
          "Solano",
          "Solita",
          "Valparaíso"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 8,
      "departamento": "Casanare",
      "ciudades": [
          "Aguazul",
          "Chameza",
          "Hato Corozal",
          "La Salina",
          "Maní",
          "Monterrey",
          "Nunchía",
          "Orocué",
          "Paz De Ariporo",
          "Pore",
          "Recetor",
          "Sabanalarga",
          "Sácama",
          "San Luis De Palenque",
          "Támara",
          "Tauramena",
          "Trinidad",
          "Villanueva",
          "Yopal"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 9,
      "departamento": "Cauca",
      "ciudades": [
          "Almaguer",
          "Argelia",
          "Balboa",
          "Bolívar",
          "Buenos Aires",
          "Cajibío",
          "Caldono",
          "Caloto",
          "Corinto",
          "El Tambo",
          "Florencia",
          "Guachené",
          "Guapí",
          "Inzá",
          "Jambaló",
          "La Sierra",
          "La Vega",
          "López De Micay",
          "Mercaderes",
          "Miranda",
          "Morales",
          "Padilla",
          "Páez",
          "Patía",
          "Piamonte",
          "Piendamó",
          "Popayán",
          "Puerto Tejada",
          "Puracé",
          "Rosas",
          "San Sebastián",
          "Santa Rosa",
          "Santander De Quilichao",
          "Silvia",
          "Sotará",
          "Suárez",
          "Sucre",
          "Timbío",
          "Timbiquí",
          "Toribio",
          "Totoró",
          "Villa Rica",
          "Guapi",
          "López",
          "Paez",
          "Sotara"
      ],
      "indicativo_fijo": "602"
  },
  {
      "id": 10,
      "departamento": "Cesar",
      "ciudades": [
          "Aguachica",
          "Agustín Codazzi",
          "Astrea",
          "Becerril",
          "Bosconia",
          "Chimichagua",
          "Chiriguaná",
          "Curumaní",
          "El Copey",
          "El Paso",
          "Gamarra",
          "González",
          "La Gloria",
          "La Jagua De Ibirico",
          "La Paz",
          "Manaure Balcón Del Cesar",
          "Pailitas",
          "Pelaya",
          "Pueblo Bello",
          "Río De Oro",
          "San Alberto",
          "San Diego",
          "San Martín",
          "Tamalameque",
          "Valledupar",
          "Manaure"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 11,
      "departamento": "Chocó",
      "ciudades": [
          "Acandí",
          "Alto Baudó",
          "Bagadó",
          "Bahía Solano",
          "Bajo Baudó",
          "Bojayá",
          "Cantón De San Pablo",
          "Cértegui",
          "Condoto",
          "El Atrato",
          "El Carmen De Atrato",
          "El Carmen Del Darién",
          "Istmina",
          "Juradó",
          "Litoral De San Juan",
          "Lloró",
          "Medio Atrato",
          "Medio Baudó",
          "Medio San Juan",
          "Nóvita",
          "Nuquí",
          "Quibdó",
          "Río Iró",
          "Río Quito",
          "Riosucio",
          "San José Del Palmar",
          "Sipí",
          "Tadó",
          "Unión Panamericana",
          "Unguía",
          "Alto Baudo",
          "Atrato",
          "Belén De Bajirá",
          "Bojaya",
          "Carmen Del Darien",
          "El Cantón Del San Pablo",
          "El Litoral Del San Juan",
          "Río Iro"
      ],
      "indicativo_fijo": "604"
  },
  {
      "id": 12,
      "departamento": "Cundinamarca",
      "ciudades": [
          "Agua De Dios",
          "Albán",
          "Anapoima",
          "Anolaima",
          "Apulo",
          "Arbeláez",
          "Beltrán",
          "Bituima",
          "Bogotá",
          "Bojacá",
          "Cabrera",
          "Cachipay",
          "Cajicá",
          "Caparrapí",
          "Cáqueza",
          "Carmen De Carupa",
          "Chaguaní",
          "Chía",
          "Chipaque",
          "Choachí",
          "Chocontá",
          "Cogua",
          "Cota",
          "Cucunubá",
          "El Colegio",
          "El Peñón",
          "El Rosal",
          "Facatativá",
          "Fómeque",
          "Fosca",
          "Funza",
          "Fúquene",
          "Fusagasugá",
          "Gachalá",
          "Gachancipá",
          "Gachetá",
          "Gama",
          "Girardot",
          "Granada",
          "Guachetá",
          "Guaduas",
          "Guasca",
          "Guataquí",
          "Guatavita",
          "Guayabal De Síquima",
          "Guayabetal",
          "Gutiérrez",
          "Jerusalén",
          "Junín",
          "La Calera",
          "La Mesa",
          "La Palma",
          "La Peña",
          "La Vega",
          "Lenguazaque",
          "Machetá",
          "Madrid",
          "Manta",
          "Medina",
          "Mosquera",
          "Nariño",
          "Nemocón",
          "Nilo",
          "Nimaima",
          "Nocaima",
          "Pacho",
          "Paime",
          "Pandi",
          "Paratebueno",
          "Pasca",
          "Puerto Salgar",
          "Pulí",
          "Quebradanegra",
          "Quetame",
          "Quipile",
          "Ricaurte",
          "San Antonio Del Tequendama",
          "San Bernardo",
          "San Cayetano",
          "San Francisco",
          "San Juan De Rioseco",
          "Sasaima",
          "Sesquilé",
          "Sibaté",
          "Silvania",
          "Simijaca",
          "Soacha",
          "Sopó",
          "Subachoque",
          "Suesca",
          "Supatá",
          "Susa",
          "Sutatausa",
          "Tabio",
          "Tausa",
          "Tena",
          "Tenjo",
          "Tibacuy",
          "Tibirita",
          "Tocaima",
          "Tocancipá",
          "Topaipí",
          "Ubalá",
          "Ubaque",
          "Ubaté",
          "Une",
          "Útica",
          "Venecia",
          "Vergara",
          "Vianí",
          "Villagómez",
          "Villapinzón",
          "Villeta",
          "Viotá",
          "Yacopí",
          "Zipacón",
          "Zipaquirá",
          "Caqueza",
          "Fomeque",
          "Gachala",
          "Guayabal De Siquima",
          "Macheta",
          "San Juan De Río Seco",
          "Villa De San Diego De Ubate"
      ],
      "indicativo_fijo": "601"
  },
  {
      "id": 13,
      "departamento": "Córdoba",
      "ciudades": [
          "Ayapel",
          "Buenavista",
          "Canalete",
          "Cereté",
          "Chimá",
          "Chinú",
          "Ciénaga De Oro",
          "Cotorra",
          "La Apartada",
          "Lorica",
          "Los Córdobas",
          "Momil",
          "Montelíbano",
          "Montería",
          "Moñitos",
          "Planeta Rica",
          "Pueblo Nuevo",
          "Puerto Escondido",
          "Puerto Libertador",
          "Purísima",
          "Sahagún",
          "San Andrés De Sotavento",
          "San Antero",
          "San Bernardo Del Viento",
          "San Carlos",
          "San José De Uré",
          "San Pelayo",
          "Tierralta",
          "Tuchín",
          "Valencia",
          "San Andrés Sotavento"
      ],
      "indicativo_fijo": "604"
  },
  {
      "id": 14,
      "departamento": "Guainía",
      "ciudades": [
          "Inírida",
          "Barranco Minas",
          "Cacahual",
          "La Guadalupe",
          "Mapiripana",
          "Morichal",
          "Pana Pana",
          "Puerto Colombia",
          "San Felipe"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 15,
      "departamento": "Guaviare",
      "ciudades": [
          "Calamar",
          "El Retorno",
          "Miraflores",
          "San José Del Guaviare"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 16,
      "departamento": "Huila",
      "ciudades": [
          "Acevedo",
          "Agrado",
          "Aipe",
          "Algeciras",
          "Altamira",
          "Baraya",
          "Campoalegre",
          "Colombia",
          "El Pital",
          "Elías",
          "Garzón",
          "Gigante",
          "Guadalupe",
          "Hobo",
          "Íquira",
          "Isnos",
          "La Argentina",
          "La Plata",
          "Nátaga",
          "Neiva",
          "Oporapa",
          "Paicol",
          "Palermo",
          "Palestina",
          "Pitalito",
          "Rivera",
          "Saladoblanco",
          "San Agustín",
          "Santa María",
          "Suaza",
          "Tarqui",
          "Tello",
          "Teruel",
          "Tesalia",
          "Timaná",
          "Villavieja",
          "Yaguará",
          "Iquira",
          "Pital"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 17,
      "departamento": "La Guajira",
      "ciudades": [
          "Albania",
          "Barrancas",
          "Dibulla",
          "Distracción",
          "El Molino",
          "Fonseca",
          "Hatonuevo",
          "La Jagua Del Pilar",
          "Maicao",
          "Manaure",
          "Riohacha",
          "San Juan Del Cesar",
          "Uribia",
          "Urumita",
          "Villanueva"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 18,
      "departamento": "Magdalena",
      "ciudades": [
          "Algarrobo",
          "Aracataca",
          "Ariguaní",
          "Cerro De San Antonio",
          "Chibolo",
          "Chibolo",
          "Ciénaga",
          "Concordia",
          "El Banco",
          "El Piñón",
          "El Retén",
          "Fundación",
          "Guamal",
          "Nueva Granada",
          "Pedraza",
          "Pijiño Del Carmen",
          "Pivijay",
          "Plato",
          "Pueblo Viejo",
          "Remolino",
          "Sabanas De San Ángel",
          "Salamina",
          "San Sebastián De Buenavista",
          "San Zenón",
          "Santa Ana",
          "Santa Bárbara De Pinto",
          "Santa Marta",
          "Sitionuevo",
          "Tenerife",
          "Zapayán",
          "Zona Bananera",
          "Cerro San Antonio",
          "El Piñon",
          "Puebloviejo",
          "Sabanas De San Angel"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 19,
      "departamento": "Meta",
      "ciudades": [
          "Acacías",
          "Barranca De Upía",
          "Cabuyaro",
          "Castilla La Nueva",
          "Cubarral",
          "Cumaral",
          "El Calvario",
          "El Castillo",
          "El Dorado",
          "Fuente De Oro",
          "Granada",
          "Guamal",
          "La Macarena",
          "La Uribe",
          "Lejanías",
          "Mapiripán",
          "Mesetas",
          "Puerto Concordia",
          "Puerto Gaitán",
          "Puerto Lleras",
          "Puerto López",
          "Puerto Rico",
          "Restrepo",
          "San Carlos De Guaroa",
          "San Juan De Arama",
          "San Juanito",
          "San Martín",
          "Villavicencio",
          "Uribe",
          "Vistahermosa"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 20,
      "departamento": "Nariño",
      "ciudades": [
          "Aldana",
          "Ancuyá",
          "Arboleda",
          "Barbacoas",
          "Belén",
          "Buesaco",
          "Chachagüí",
          "Colón",
          "Consacá",
          "Contadero",
          "Córdoba",
          "Cuaspud",
          "Cumbal",
          "Cumbitara",
          "El Charco",
          "El Peñol",
          "El Rosario",
          "El Tablón",
          "El Tambo",
          "Francisco Pizarro",
          "Funes",
          "Guachucal",
          "Guaitarilla",
          "Gualmatán",
          "Iles",
          "Imués",
          "Ipiales",
          "La Cruz",
          "La Florida",
          "La Llanada",
          "La Tola",
          "La Unión",
          "Leiva",
          "Linares",
          "Los Andes",
          "Magüí Payán",
          "Mallama",
          "Mosquera",
          "Nariño",
          "Olaya Herrera",
          "Ospina",
          "Pasto",
          "Policarpa",
          "Potosí",
          "Providencia",
          "Puerres",
          "Pupiales",
          "Ricaurte",
          "Roberto Payán",
          "Samaniego",
          "San Bernardo",
          "San José De Albán",
          "San Lorenzo",
          "San Pablo",
          "San Pedro De Cartago",
          "Sandoná",
          "Santa Bárbara",
          "Santacruz",
          "Sapuyes",
          "Taminango",
          "Tangua",
          "Tumaco",
          "Túquerres",
          "Yacuanquer",
          "Albán",
          "Consaca",
          "El Tablón De Gómez",
          "Magüi"
      ],
      "indicativo_fijo": "602"
  },
  {
      "id": 21,
      "departamento": "Norte de Santander",
      "ciudades": [
          "Ábrego",
          "Arboledas",
          "Bochalema",
          "Bucarasica",
          "Cáchira",
          "Cácota",
          "Chinácota",
          "Chitagá",
          "Convención",
          "Cúcuta",
          "Cucutilla",
          "Duranía",
          "El Carmen",
          "El Tarra",
          "El Zulia",
          "Gramalote",
          "Hacarí",
          "Herrán",
          "La Esperanza",
          "La Playa De Belén",
          "Labateca",
          "Los Patios",
          "Lourdes",
          "Mutiscua",
          "Ocaña",
          "Pamplona",
          "Pamplonita",
          "Puerto Santander",
          "Ragonvalia",
          "Salazar De Las Palmas",
          "San Calixto",
          "San Cayetano",
          "Santiago",
          "Santo Domingo De Silos",
          "Sardinata",
          "Teorama",
          "Tibú",
          "Toledo",
          "Villa Caro",
          "Villa Del Rosario",
          "Abrego",
          "Cachirá",
          "Durania",
          "La Playa",
          "Salazar",
          "Silos"
      ],
      "indicativo_fijo": "607"
  },
  {
      "id": 22,
      "departamento": "Putumayo",
      "ciudades": [
          "Colón",
          "Mocoa",
          "Orito",
          "Puerto Asís",
          "Puerto Caicedo",
          "Puerto Guzmán",
          "Puerto Leguízamo",
          "San Francisco",
          "San Miguel",
          "Santiago",
          "Sibundoy",
          "Valle Del Guamuez",
          "Villagarzón",
          "Leguízamo"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 23,
      "departamento": "Quindio",
      "ciudades": [
          "Armenia",
          "Buenavista",
          "Calarca",
          "Circasia",
          "Córdoba",
          "Filandia",
          "Génova",
          "La Tebaida",
          "Montenegro",
          "Pijao",
          "Quimbaya",
          "Salento"
      ],
      "indicativo_fijo": "606"
  },
  {
      "id": 24,
      "departamento": "Risaralda",
      "ciudades": [
          "Apía",
          "Balboa",
          "Belén De Umbría",
          "Dosquebradas",
          "Guática",
          "La Celia",
          "La Virginia",
          "Marsella",
          "Mistrató",
          "Pereira",
          "Pueblo Rico",
          "Quinchía",
          "Santa Rosa De Cabal",
          "Santuario"
      ],
      "indicativo_fijo": "606"
  },
  {
      "id": 25,
      "departamento": "San Andrés y Providencia",
      "ciudades": [
          "Providencia y Santa Catalina Islas",
          "San Andrés"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 26,
      "departamento": "Santander",
      "ciudades": [
          "Aguada",
          "Albania",
          "Aratoca",
          "Barbosa",
          "Barichara",
          "Barrancabermeja",
          "Betulia",
          "Bolívar",
          "Bucaramanga",
          "Cabrera",
          "California",
          "Capitanejo",
          "Carcasí",
          "Cepitá",
          "Cerrito",
          "Charalá",
          "Charta",
          "Chima",
          "Chipatá",
          "Cimitarra",
          "Concepción",
          "Confines",
          "Contratación",
          "Coromoro",
          "Curití",
          "El Carmen De Chucurí",
          "El Guacamayo",
          "El Peñón",
          "El Playón",
          "El Socorro",
          "Encino",
          "Enciso",
          "Florián",
          "Floridablanca",
          "Galán",
          "Gámbita",
          "Girón",
          "Guaca",
          "Guadalupe",
          "Guapotá",
          "Guavatá",
          "Güepsa",
          "Hato",
          "Jesús María",
          "Jordán",
          "La Belleza",
          "La Paz",
          "Landázuri",
          "Lebrija",
          "Los Santos",
          "Macaravita",
          "Málaga",
          "Matanza",
          "Mogotes",
          "Molagavita",
          "Ocamonte",
          "Oiba",
          "Onzaga",
          "Palmar",
          "Palmas Del Socorro",
          "Páramo",
          "Piedecuesta",
          "Pinchote",
          "Puente Nacional",
          "Puerto Parra",
          "Puerto Wilches",
          "Rionegro",
          "Sabana De Torres",
          "San Andrés",
          "San Benito",
          "San Gil",
          "San Joaquín",
          "San José De Miranda",
          "San Miguel",
          "San Vicente De Chucurí",
          "Santa Bárbara",
          "Santa Helena Del Opón",
          "Simacota",
          "Suaita",
          "Sucre",
          "Suratá",
          "Tona",
          "Valle De San José",
          "Vélez",
          "Vetas",
          "Villanueva",
          "Zapatoca",
          "Gambita",
          "Lebríja",
          "Socorro"
      ],
      "indicativo_fijo": "607"
  },
  {
      "id": 27,
      "departamento": "Sucre",
      "ciudades": [
          "Buenavista",
          "Caimito",
          "Chalán",
          "Colosó",
          "Corozal",
          "Coveñas",
          "El Roble",
          "Galeras",
          "Guaranda",
          "La Unión",
          "Los Palmitos",
          "Majagual",
          "Morroa",
          "Ovejas",
          "Sampués",
          "San Antonio De Palmito",
          "San Benito Abad",
          "San Juan De Betulia",
          "San Marcos",
          "San Onofre",
          "San Pedro",
          "Sincé",
          "Sincelejo",
          "Sucre",
          "Tolú",
          "Tolú Viejo",
          "Coloso",
          "Palmito",
          "Santiago De Tolú"
      ],
      "indicativo_fijo": "605"
  },
  {
      "id": 28,
      "departamento": "Tolima",
      "ciudades": [
          "Alpujarra",
          "Alvarado",
          "Ambalema",
          "Anzoátegui",
          "Armero",
          "Ataco",
          "Cajamarca",
          "Carmen De Apicalá",
          "Casabianca",
          "Chaparral",
          "Coello",
          "Coyaima",
          "Cunday",
          "Dolores",
          "El Espinal",
          "Falán",
          "Flandes",
          "Fresno",
          "Guamo",
          "Herveo",
          "Honda",
          "Ibagué",
          "Icononzo",
          "Lérida",
          "Líbano",
          "Mariquita",
          "Melgar",
          "Murillo",
          "Natagaima",
          "Ortega",
          "Palocabildo",
          "Piedras",
          "Planadas",
          "Prado",
          "Purificación",
          "Rioblanco",
          "Roncesvalles",
          "Rovira",
          "Saldaña",
          "San Antonio",
          "San Luis",
          "Santa Isabel",
          "Suárez",
          "Valle De San Juan",
          "Venadillo",
          "Villahermosa",
          "Villarrica",
          "Espinal",
          "Falan"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 29,
      "departamento": "Valle del Cauca",
      "ciudades": [
          "Alcalá",
          "Andalucía",
          "Ansermanuevo",
          "Argelia",
          "Bolívar",
          "Buenaventura",
          "Buga",
          "Bugalagrande",
          "Caicedonia",
          "Cali",
          "Calima",
          "Candelaria",
          "Cartago",
          "Dagua",
          "El Águila",
          "El Cairo",
          "El Cerrito",
          "El Dovio",
          "Florida",
          "Ginebra",
          "Guacarí",
          "Jamundí",
          "La Cumbre",
          "La Unión",
          "La Victoria",
          "Obando",
          "Palmira",
          "Pradera",
          "Restrepo",
          "Riofrío",
          "Roldanillo",
          "San Pedro",
          "Sevilla",
          "Toro",
          "Trujillo",
          "Tuluá",
          "Ulloa",
          "Versalles",
          "Vijes",
          "Yotoco",
          "Yumbo",
          "Zarzal",
          "Guadalajara De Buga"
      ],
      "indicativo_fijo": "602"
  },
  {
      "id": 30,
      "departamento": "Vaupés",
      "ciudades": [
          "Caruru",
          "Mitú",
          "Taraira",
          "Pacoa",
          "Papunaua",
          "Yavaraté"
      ],
      "indicativo_fijo": "608"
  },
  {
      "id": 31,
      "departamento": "Vichada",
      "ciudades": [
          "Cumaribo",
          "La Primavera",
          "Puerto Carreño",
          "Santa Rosalía"
      ],
      "indicativo_fijo": "608"
  }
]